import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myFavicon.ico" />
      </Head>
      <header>
        
      </header>
      <main className="bg-slate-600 min-h-screen">
        <div className="bg-red-600">hello world</div>
      </main>
    </>
  );
}
