import Head from "next/head";
import Link from "next/link";
import link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myFavicon.ico" />
      </Head>
      <header>
      <nav>
        <ul>
          <li><Link></Link></li>
          <li><Link></Link></li>
          <li><Link></Link></li>
        </ul>
      </nav>
      </header>
      <main className="bg-slate-600 min-h-screen">
        <div className="bg-red-600">hello world</div>
      </main>
    </>
  );
}
